[pytest]

python_files = test_*.py
python_functions = test_*

addopts = -vv -s -p no:cacheprovider
# -vv — настройка вывода информации о прохождении тестов.
# -s — отключает перехват вывода (stdout/stderr).
# -p no:cacheprovider — отключает кэширование результатов тестов.

markers =
    smoke: быстрая проверка основных функций
    regression: полная проверка функционала
